log_path: logs
log_name: monitor
log_level: 2
log_file_size: 100000000
log_file_count: 100
http_listen_port: :2234
mysql_address: vmhost
mysql_port: 3306
mysql_user: datasys
mysql_pwd: datasys
mysql_db_name: monitor
key_file:
key_pwd:
