log_path: logs
log_name: server
log_file_size: 100000000
log_file_count: 100
log_level: 2
http_listen_port: :51204
http_template_path: templates
http_cookie_secret: 5TYHJMGHUIHNrfvgho-0ugbhyhhhjf5r
http_session_id: secret_session_id
http_access_time: secret_access_time
http_session_timeout: 900
oauth_app_id: app_id
oauth_app_secret: app_secret
oauth_redirect_url: my_url
oauth_user_url: user_url
oauth_auth_url: auth_url
oauth_token_url: token_url
mysql_address: vmhost
mysql_port: 3306
mysql_user: datasys
mysql_pwd: datasys
mysql_db_name: monitor
server_local_mode: true